{% set version = "7.0.0" %}

package:
    name: ferret_datasets
    version: {{ version }}

source:
    fn: ferret_datasets-{{ version }}.tar.gz
    url: https://github.com/NOAA-PMEL/FerretDatasets/archive/v{{ version }}.tar.gz
    sha256: 03f48624b141f15fb67cfb19bf9937dc2cc13b3c280e08caf46e15e4b2b71542

build:
    number: 0
    skip: True  # [win or py3k]

requirements:
    build:
        - python
        - pyferret
    run:
        - python
        - pyferret

test:
    imports:
        - pyferret

about:
    home: http://ferret.pmel.noaa.gov/Ferret
    license: MIT
    summary: 'Data for pyferret examples.'

extra:
    recipe-maintainers:
        - eugeneburger
        - karlmsmith
        - ocefpaf
