travis:
  secure:
    BINSTAR_TOKEN: TpU1Nt4nR/zoR4ovkwm6yvKKBDIj3K8/yBofkqj1qeX9i8seFawyp1mHFZHx1qu6qBK+RJT3xuqVft6FftfD3eQFtePuVkx04SOiptIjbenq+WqGr/j1DlK6ifLpxJR1XSZAqy/6SwUKjFpd95aNWI4H7jFsFioEkGT9KhI0oa8ABJMG5y5VAqz0t+5dRS8freF+uoHkDsScGvEtjNIFJO+uXNYVXJkl7kVR/wAwSAsDXYmtOIhbgl0mF1agUnkVbpitIQAwi8DDQsk4tiMLHw+0YwI1ILerv220viC7uxCFmqLtiCvIG59TAWa/jso0srBWSc+bTu+MEbbjW1XPirVksQWUENPVgB5zI6HPyYXQ35EnsnIBFIUXEMdJinZ6aG/X+kp8JpTgGaFZElCtqA7cluSWMlaFi3u3S5WmFFf0QcvMgDZzqWBr0d4bDQxOkXnIlQ+N4nkdNNSOzEnsM3fLxV773GGPi1v4Any7/8h24g6pk0iOaoizNbs/Y0lor9l98I7modL1YOjTSYGxGuyFV+8hFi0g2wbkdvfo4XHnqejjdKP4vlRJ+Ymp+s8RoARGus01wUCuzTP58nTd6yjfA9VMsHnx5n1nwMKmWSzUhg30ERRC1EfiEVM4WYYeCD05+T/WiC0BCBYoBnsh2fMIq8ecd7SnmU2339YW54g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
